sudo: required

language: cpp

services:
  - docker
  
branches:
  only: 
  - master
  
before_install:
- docker run -d --name ubuntu-xenial -v $(pwd):/build ubuntu:xenial tail -f /dev/null
- docker ps -a

install: 
- docker exec -t ubuntu-xenial bash -c "add-apt-repository ppa:djcj/vapoursynth -y"
- docker exec -t ubuntu-xenial bash -c "apt-get update -qq"
- docker exec -t ubuntu-xenial bash -c "install -y libvapoursynth-dev meson ocl-icd-opencl-dev"

script: 
- docker exec -t ubuntu-xenial bash -c "cd / travis"
- docker exec -t ubuntu-xenial bash -c "ninja -v -C build"

notifications:
  email: false
