language: cpp

branches:
  only: 
  - master
  
before_install:
- sudo add-apt-repository ppa:djcj/vapoursynth -y
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install g++-5 ocl-icd-libopencl1 ocl-icd-opencl-dev opencl-headers libvapoursynth-dev python3-pip
  
install:
- mkdir build && export PATH="`pwd`/build:${PATH}"
- wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
- sudo pip3 install meson==0.44

script: 
- CC=/usr/bin/g++-5.4.1 meson build
- ninja -v -C build

notifications:
  email: false
