name: Build for Windows

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ windows-latest ]
        arch: [ x64 ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v4
      if: steps.cache-fftw3.outputs.cache-hit != 'true'
      with:
        vcpkgArguments: 'opencl:x64-windows boost-filesystem:x64-windows-static boost-system:x64-windows-static'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092 # 2021.05.12 release

#    - name: Upload vcpkg artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: vcpkg-${{matrix.arch}}
#        path: |
#          ${{ github.workspace }}/vcpkg/installed

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: install meson and ninja
      run: pip install meson ninja

    - name: download VS headers and patch header location
      shell: bash
      run: |
        git clone https://github.com/AmusementClub/vapoursynth-classic --depth=1 --branch doodle2 vapoursynth
        cp vapoursynth/include/*.h KNLMeansCL/
        sed -i -e '/#include <V/y|<>|""|' KNLMeansCL/NLMVapoursynth.h

    - name: download avisynth header and patch header location
      shell: bash
      run: |
        git clone https://github.com/AviSynth/AviSynthPlus/ --depth=1 avisynthplus
        cp -r avisynthplus/avs_core/include/* KNLMeansCL/
        sed -i -e '/# *include <avisynth/y|<>|""|' KNLMeansCL/NLMAvisynth.h

    - name: setup MS dev commands
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Install pkg-config lite
      run: choco install pkgconfiglite

    - name: Meson setup
      run: meson setup builddir/ -Db_vscrt=mt -Dpkg_config_path=${{ github.workspace }}/vcpkg/installed/x64-windows/lib/pkgconfig:${{ github.workspace }}/vcpkg/installed/x64-windows-static/lib/pkgconfig
      env:
        BOOST_ROOT: ${{ github.workspace }}/vcpkg/installed/x64-windows-static
        OPENCL_ROOT: ${{ github.workspace }}/vcpkg/installed/x64-windows
      #env:
      #  CXX: clang-cl
      #  CXXFLAGS: "-mavx -mfma -Xclang -ffast-math"

    - name: Meson compile
      run: meson compile -C builddir/ -v

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-${{matrix.arch}}
        path: |
          builddir/*.dll

